# cargo-features = [ "profile-rustflags" ]

[package]
authors = ["Aaron Pribadi <aaron.pribadi@gmail.com>"]
edition = "2024"
license = "Artistic-2.0"
name = "tangerine"
version = "0.1.0"

[lints.rust]
elided_lifetimes_in_paths = "warn"
non_ascii_idents = "warn"
private_bounds = "allow"
trivial_numeric_casts = "warn"
unreachable_pub = "warn"
unsafe_op_in_unsafe_fn = "deny"
unused_lifetimes = "warn"
unused_qualifications = "warn"
unused_results = "warn"

[dependencies]
dandelion-random = { version = "0.2.0", features = ["rand_core", "thread_local"] }
rand_core = { version = "0.9.3" }

[dev-dependencies]
expect-test = { version = "1.5.1" }

[profile.release]
# rustflags = [ "-C", "no-vectorize-loops", "-C", "no-vectorize-slp" ]

[profile.dev]
